
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Users` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model Users
 * 
 */
export type UsersModel = runtime.Types.Result.DefaultSelection<Prisma.$UsersPayload>

export type AggregateUsers = {
  _count: UsersCountAggregateOutputType | null
  _min: UsersMinAggregateOutputType | null
  _max: UsersMaxAggregateOutputType | null
}

export type UsersMinAggregateOutputType = {
  id: string | null
  name: string | null
  email: string | null
  email_verified: boolean | null
  image: string | null
  created_at: Date | null
  updated_at: Date | null
  username: string | null
  display_username: string | null
}

export type UsersMaxAggregateOutputType = {
  id: string | null
  name: string | null
  email: string | null
  email_verified: boolean | null
  image: string | null
  created_at: Date | null
  updated_at: Date | null
  username: string | null
  display_username: string | null
}

export type UsersCountAggregateOutputType = {
  id: number
  name: number
  email: number
  email_verified: number
  image: number
  created_at: number
  updated_at: number
  username: number
  display_username: number
  _all: number
}


export type UsersMinAggregateInputType = {
  id?: true
  name?: true
  email?: true
  email_verified?: true
  image?: true
  created_at?: true
  updated_at?: true
  username?: true
  display_username?: true
}

export type UsersMaxAggregateInputType = {
  id?: true
  name?: true
  email?: true
  email_verified?: true
  image?: true
  created_at?: true
  updated_at?: true
  username?: true
  display_username?: true
}

export type UsersCountAggregateInputType = {
  id?: true
  name?: true
  email?: true
  email_verified?: true
  image?: true
  created_at?: true
  updated_at?: true
  username?: true
  display_username?: true
  _all?: true
}

export type UsersAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Users to aggregate.
   */
  where?: Prisma.UsersWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Users to fetch.
   */
  orderBy?: Prisma.UsersOrderByWithRelationInput | Prisma.UsersOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.UsersWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Users from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Users.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Users
  **/
  _count?: true | UsersCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: UsersMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: UsersMaxAggregateInputType
}

export type GetUsersAggregateType<T extends UsersAggregateArgs> = {
      [P in keyof T & keyof AggregateUsers]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateUsers[P]>
    : Prisma.GetScalarType<T[P], AggregateUsers[P]>
}




export type UsersGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.UsersWhereInput
  orderBy?: Prisma.UsersOrderByWithAggregationInput | Prisma.UsersOrderByWithAggregationInput[]
  by: Prisma.UsersScalarFieldEnum[] | Prisma.UsersScalarFieldEnum
  having?: Prisma.UsersScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: UsersCountAggregateInputType | true
  _min?: UsersMinAggregateInputType
  _max?: UsersMaxAggregateInputType
}

export type UsersGroupByOutputType = {
  id: string
  name: string
  email: string
  email_verified: boolean
  image: string | null
  created_at: Date
  updated_at: Date
  username: string | null
  display_username: string | null
  _count: UsersCountAggregateOutputType | null
  _min: UsersMinAggregateOutputType | null
  _max: UsersMaxAggregateOutputType | null
}

type GetUsersGroupByPayload<T extends UsersGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<UsersGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof UsersGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], UsersGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], UsersGroupByOutputType[P]>
      }
    >
  >



export type UsersWhereInput = {
  AND?: Prisma.UsersWhereInput | Prisma.UsersWhereInput[]
  OR?: Prisma.UsersWhereInput[]
  NOT?: Prisma.UsersWhereInput | Prisma.UsersWhereInput[]
  id?: Prisma.UuidFilter<"Users"> | string
  name?: Prisma.StringFilter<"Users"> | string
  email?: Prisma.StringFilter<"Users"> | string
  email_verified?: Prisma.BoolFilter<"Users"> | boolean
  image?: Prisma.StringNullableFilter<"Users"> | string | null
  created_at?: Prisma.DateTimeFilter<"Users"> | Date | string
  updated_at?: Prisma.DateTimeFilter<"Users"> | Date | string
  username?: Prisma.StringNullableFilter<"Users"> | string | null
  display_username?: Prisma.StringNullableFilter<"Users"> | string | null
  sessionss?: Prisma.SessionsListRelationFilter
  accountss?: Prisma.AccountsListRelationFilter
}

export type UsersOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  email?: Prisma.SortOrder
  email_verified?: Prisma.SortOrder
  image?: Prisma.SortOrderInput | Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
  username?: Prisma.SortOrderInput | Prisma.SortOrder
  display_username?: Prisma.SortOrderInput | Prisma.SortOrder
  sessionss?: Prisma.SessionsOrderByRelationAggregateInput
  accountss?: Prisma.AccountsOrderByRelationAggregateInput
}

export type UsersWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  email?: string
  username?: string
  AND?: Prisma.UsersWhereInput | Prisma.UsersWhereInput[]
  OR?: Prisma.UsersWhereInput[]
  NOT?: Prisma.UsersWhereInput | Prisma.UsersWhereInput[]
  name?: Prisma.StringFilter<"Users"> | string
  email_verified?: Prisma.BoolFilter<"Users"> | boolean
  image?: Prisma.StringNullableFilter<"Users"> | string | null
  created_at?: Prisma.DateTimeFilter<"Users"> | Date | string
  updated_at?: Prisma.DateTimeFilter<"Users"> | Date | string
  display_username?: Prisma.StringNullableFilter<"Users"> | string | null
  sessionss?: Prisma.SessionsListRelationFilter
  accountss?: Prisma.AccountsListRelationFilter
}, "id" | "email" | "username">

export type UsersOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  email?: Prisma.SortOrder
  email_verified?: Prisma.SortOrder
  image?: Prisma.SortOrderInput | Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
  username?: Prisma.SortOrderInput | Prisma.SortOrder
  display_username?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.UsersCountOrderByAggregateInput
  _max?: Prisma.UsersMaxOrderByAggregateInput
  _min?: Prisma.UsersMinOrderByAggregateInput
}

export type UsersScalarWhereWithAggregatesInput = {
  AND?: Prisma.UsersScalarWhereWithAggregatesInput | Prisma.UsersScalarWhereWithAggregatesInput[]
  OR?: Prisma.UsersScalarWhereWithAggregatesInput[]
  NOT?: Prisma.UsersScalarWhereWithAggregatesInput | Prisma.UsersScalarWhereWithAggregatesInput[]
  id?: Prisma.UuidWithAggregatesFilter<"Users"> | string
  name?: Prisma.StringWithAggregatesFilter<"Users"> | string
  email?: Prisma.StringWithAggregatesFilter<"Users"> | string
  email_verified?: Prisma.BoolWithAggregatesFilter<"Users"> | boolean
  image?: Prisma.StringNullableWithAggregatesFilter<"Users"> | string | null
  created_at?: Prisma.DateTimeWithAggregatesFilter<"Users"> | Date | string
  updated_at?: Prisma.DateTimeWithAggregatesFilter<"Users"> | Date | string
  username?: Prisma.StringNullableWithAggregatesFilter<"Users"> | string | null
  display_username?: Prisma.StringNullableWithAggregatesFilter<"Users"> | string | null
}

export type UsersCreateInput = {
  id?: string
  name: string
  email: string
  email_verified?: boolean
  image?: string | null
  created_at?: Date | string
  updated_at?: Date | string
  username?: string | null
  display_username?: string | null
  sessionss?: Prisma.SessionsCreateNestedManyWithoutUsersInput
  accountss?: Prisma.AccountsCreateNestedManyWithoutUsersInput
}

export type UsersUncheckedCreateInput = {
  id?: string
  name: string
  email: string
  email_verified?: boolean
  image?: string | null
  created_at?: Date | string
  updated_at?: Date | string
  username?: string | null
  display_username?: string | null
  sessionss?: Prisma.SessionsUncheckedCreateNestedManyWithoutUsersInput
  accountss?: Prisma.AccountsUncheckedCreateNestedManyWithoutUsersInput
}

export type UsersUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  email_verified?: Prisma.BoolFieldUpdateOperationsInput | boolean
  image?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  username?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  display_username?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  sessionss?: Prisma.SessionsUpdateManyWithoutUsersNestedInput
  accountss?: Prisma.AccountsUpdateManyWithoutUsersNestedInput
}

export type UsersUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  email_verified?: Prisma.BoolFieldUpdateOperationsInput | boolean
  image?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  username?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  display_username?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  sessionss?: Prisma.SessionsUncheckedUpdateManyWithoutUsersNestedInput
  accountss?: Prisma.AccountsUncheckedUpdateManyWithoutUsersNestedInput
}

export type UsersCreateManyInput = {
  id?: string
  name: string
  email: string
  email_verified?: boolean
  image?: string | null
  created_at?: Date | string
  updated_at?: Date | string
  username?: string | null
  display_username?: string | null
}

export type UsersUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  email_verified?: Prisma.BoolFieldUpdateOperationsInput | boolean
  image?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  username?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  display_username?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type UsersUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  email_verified?: Prisma.BoolFieldUpdateOperationsInput | boolean
  image?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  username?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  display_username?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type UsersCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  email?: Prisma.SortOrder
  email_verified?: Prisma.SortOrder
  image?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
  username?: Prisma.SortOrder
  display_username?: Prisma.SortOrder
}

export type UsersMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  email?: Prisma.SortOrder
  email_verified?: Prisma.SortOrder
  image?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
  username?: Prisma.SortOrder
  display_username?: Prisma.SortOrder
}

export type UsersMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  email?: Prisma.SortOrder
  email_verified?: Prisma.SortOrder
  image?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
  username?: Prisma.SortOrder
  display_username?: Prisma.SortOrder
}

export type UsersScalarRelationFilter = {
  is?: Prisma.UsersWhereInput
  isNot?: Prisma.UsersWhereInput
}

export type StringFieldUpdateOperationsInput = {
  set?: string
}

export type BoolFieldUpdateOperationsInput = {
  set?: boolean
}

export type NullableStringFieldUpdateOperationsInput = {
  set?: string | null
}

export type DateTimeFieldUpdateOperationsInput = {
  set?: Date | string
}

export type UsersCreateNestedOneWithoutSessionssInput = {
  create?: Prisma.XOR<Prisma.UsersCreateWithoutSessionssInput, Prisma.UsersUncheckedCreateWithoutSessionssInput>
  connectOrCreate?: Prisma.UsersCreateOrConnectWithoutSessionssInput
  connect?: Prisma.UsersWhereUniqueInput
}

export type UsersUpdateOneRequiredWithoutSessionssNestedInput = {
  create?: Prisma.XOR<Prisma.UsersCreateWithoutSessionssInput, Prisma.UsersUncheckedCreateWithoutSessionssInput>
  connectOrCreate?: Prisma.UsersCreateOrConnectWithoutSessionssInput
  upsert?: Prisma.UsersUpsertWithoutSessionssInput
  connect?: Prisma.UsersWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.UsersUpdateToOneWithWhereWithoutSessionssInput, Prisma.UsersUpdateWithoutSessionssInput>, Prisma.UsersUncheckedUpdateWithoutSessionssInput>
}

export type UsersCreateNestedOneWithoutAccountssInput = {
  create?: Prisma.XOR<Prisma.UsersCreateWithoutAccountssInput, Prisma.UsersUncheckedCreateWithoutAccountssInput>
  connectOrCreate?: Prisma.UsersCreateOrConnectWithoutAccountssInput
  connect?: Prisma.UsersWhereUniqueInput
}

export type UsersUpdateOneRequiredWithoutAccountssNestedInput = {
  create?: Prisma.XOR<Prisma.UsersCreateWithoutAccountssInput, Prisma.UsersUncheckedCreateWithoutAccountssInput>
  connectOrCreate?: Prisma.UsersCreateOrConnectWithoutAccountssInput
  upsert?: Prisma.UsersUpsertWithoutAccountssInput
  connect?: Prisma.UsersWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.UsersUpdateToOneWithWhereWithoutAccountssInput, Prisma.UsersUpdateWithoutAccountssInput>, Prisma.UsersUncheckedUpdateWithoutAccountssInput>
}

export type UsersCreateWithoutSessionssInput = {
  id?: string
  name: string
  email: string
  email_verified?: boolean
  image?: string | null
  created_at?: Date | string
  updated_at?: Date | string
  username?: string | null
  display_username?: string | null
  accountss?: Prisma.AccountsCreateNestedManyWithoutUsersInput
}

export type UsersUncheckedCreateWithoutSessionssInput = {
  id?: string
  name: string
  email: string
  email_verified?: boolean
  image?: string | null
  created_at?: Date | string
  updated_at?: Date | string
  username?: string | null
  display_username?: string | null
  accountss?: Prisma.AccountsUncheckedCreateNestedManyWithoutUsersInput
}

export type UsersCreateOrConnectWithoutSessionssInput = {
  where: Prisma.UsersWhereUniqueInput
  create: Prisma.XOR<Prisma.UsersCreateWithoutSessionssInput, Prisma.UsersUncheckedCreateWithoutSessionssInput>
}

export type UsersUpsertWithoutSessionssInput = {
  update: Prisma.XOR<Prisma.UsersUpdateWithoutSessionssInput, Prisma.UsersUncheckedUpdateWithoutSessionssInput>
  create: Prisma.XOR<Prisma.UsersCreateWithoutSessionssInput, Prisma.UsersUncheckedCreateWithoutSessionssInput>
  where?: Prisma.UsersWhereInput
}

export type UsersUpdateToOneWithWhereWithoutSessionssInput = {
  where?: Prisma.UsersWhereInput
  data: Prisma.XOR<Prisma.UsersUpdateWithoutSessionssInput, Prisma.UsersUncheckedUpdateWithoutSessionssInput>
}

export type UsersUpdateWithoutSessionssInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  email_verified?: Prisma.BoolFieldUpdateOperationsInput | boolean
  image?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  username?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  display_username?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  accountss?: Prisma.AccountsUpdateManyWithoutUsersNestedInput
}

export type UsersUncheckedUpdateWithoutSessionssInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  email_verified?: Prisma.BoolFieldUpdateOperationsInput | boolean
  image?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  username?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  display_username?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  accountss?: Prisma.AccountsUncheckedUpdateManyWithoutUsersNestedInput
}

export type UsersCreateWithoutAccountssInput = {
  id?: string
  name: string
  email: string
  email_verified?: boolean
  image?: string | null
  created_at?: Date | string
  updated_at?: Date | string
  username?: string | null
  display_username?: string | null
  sessionss?: Prisma.SessionsCreateNestedManyWithoutUsersInput
}

export type UsersUncheckedCreateWithoutAccountssInput = {
  id?: string
  name: string
  email: string
  email_verified?: boolean
  image?: string | null
  created_at?: Date | string
  updated_at?: Date | string
  username?: string | null
  display_username?: string | null
  sessionss?: Prisma.SessionsUncheckedCreateNestedManyWithoutUsersInput
}

export type UsersCreateOrConnectWithoutAccountssInput = {
  where: Prisma.UsersWhereUniqueInput
  create: Prisma.XOR<Prisma.UsersCreateWithoutAccountssInput, Prisma.UsersUncheckedCreateWithoutAccountssInput>
}

export type UsersUpsertWithoutAccountssInput = {
  update: Prisma.XOR<Prisma.UsersUpdateWithoutAccountssInput, Prisma.UsersUncheckedUpdateWithoutAccountssInput>
  create: Prisma.XOR<Prisma.UsersCreateWithoutAccountssInput, Prisma.UsersUncheckedCreateWithoutAccountssInput>
  where?: Prisma.UsersWhereInput
}

export type UsersUpdateToOneWithWhereWithoutAccountssInput = {
  where?: Prisma.UsersWhereInput
  data: Prisma.XOR<Prisma.UsersUpdateWithoutAccountssInput, Prisma.UsersUncheckedUpdateWithoutAccountssInput>
}

export type UsersUpdateWithoutAccountssInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  email_verified?: Prisma.BoolFieldUpdateOperationsInput | boolean
  image?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  username?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  display_username?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  sessionss?: Prisma.SessionsUpdateManyWithoutUsersNestedInput
}

export type UsersUncheckedUpdateWithoutAccountssInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  email_verified?: Prisma.BoolFieldUpdateOperationsInput | boolean
  image?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  username?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  display_username?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  sessionss?: Prisma.SessionsUncheckedUpdateManyWithoutUsersNestedInput
}


/**
 * Count Type UsersCountOutputType
 */

export type UsersCountOutputType = {
  sessionss: number
  accountss: number
}

export type UsersCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  sessionss?: boolean | UsersCountOutputTypeCountSessionssArgs
  accountss?: boolean | UsersCountOutputTypeCountAccountssArgs
}

/**
 * UsersCountOutputType without action
 */
export type UsersCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UsersCountOutputType
   */
  select?: Prisma.UsersCountOutputTypeSelect<ExtArgs> | null
}

/**
 * UsersCountOutputType without action
 */
export type UsersCountOutputTypeCountSessionssArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.SessionsWhereInput
}

/**
 * UsersCountOutputType without action
 */
export type UsersCountOutputTypeCountAccountssArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.AccountsWhereInput
}


export type UsersSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  email?: boolean
  email_verified?: boolean
  image?: boolean
  created_at?: boolean
  updated_at?: boolean
  username?: boolean
  display_username?: boolean
  sessionss?: boolean | Prisma.Users$sessionssArgs<ExtArgs>
  accountss?: boolean | Prisma.Users$accountssArgs<ExtArgs>
  _count?: boolean | Prisma.UsersCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["users"]>

export type UsersSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  email?: boolean
  email_verified?: boolean
  image?: boolean
  created_at?: boolean
  updated_at?: boolean
  username?: boolean
  display_username?: boolean
}, ExtArgs["result"]["users"]>

export type UsersSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  email?: boolean
  email_verified?: boolean
  image?: boolean
  created_at?: boolean
  updated_at?: boolean
  username?: boolean
  display_username?: boolean
}, ExtArgs["result"]["users"]>

export type UsersSelectScalar = {
  id?: boolean
  name?: boolean
  email?: boolean
  email_verified?: boolean
  image?: boolean
  created_at?: boolean
  updated_at?: boolean
  username?: boolean
  display_username?: boolean
}

export type UsersOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "name" | "email" | "email_verified" | "image" | "created_at" | "updated_at" | "username" | "display_username", ExtArgs["result"]["users"]>
export type UsersInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  sessionss?: boolean | Prisma.Users$sessionssArgs<ExtArgs>
  accountss?: boolean | Prisma.Users$accountssArgs<ExtArgs>
  _count?: boolean | Prisma.UsersCountOutputTypeDefaultArgs<ExtArgs>
}
export type UsersIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}
export type UsersIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}

export type $UsersPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Users"
  objects: {
    sessionss: Prisma.$SessionsPayload<ExtArgs>[]
    accountss: Prisma.$AccountsPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    name: string
    email: string
    email_verified: boolean
    image: string | null
    created_at: Date
    updated_at: Date
    username: string | null
    display_username: string | null
  }, ExtArgs["result"]["users"]>
  composites: {}
}

export type UsersGetPayload<S extends boolean | null | undefined | UsersDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$UsersPayload, S>

export type UsersCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<UsersFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: UsersCountAggregateInputType | true
  }

export interface UsersDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Users'], meta: { name: 'Users' } }
  /**
   * Find zero or one Users that matches the filter.
   * @param {UsersFindUniqueArgs} args - Arguments to find a Users
   * @example
   * // Get one Users
   * const users = await prisma.users.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends UsersFindUniqueArgs>(args: Prisma.SelectSubset<T, UsersFindUniqueArgs<ExtArgs>>): Prisma.Prisma__UsersClient<runtime.Types.Result.GetResult<Prisma.$UsersPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Users that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {UsersFindUniqueOrThrowArgs} args - Arguments to find a Users
   * @example
   * // Get one Users
   * const users = await prisma.users.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends UsersFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, UsersFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__UsersClient<runtime.Types.Result.GetResult<Prisma.$UsersPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Users that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UsersFindFirstArgs} args - Arguments to find a Users
   * @example
   * // Get one Users
   * const users = await prisma.users.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends UsersFindFirstArgs>(args?: Prisma.SelectSubset<T, UsersFindFirstArgs<ExtArgs>>): Prisma.Prisma__UsersClient<runtime.Types.Result.GetResult<Prisma.$UsersPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Users that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UsersFindFirstOrThrowArgs} args - Arguments to find a Users
   * @example
   * // Get one Users
   * const users = await prisma.users.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends UsersFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, UsersFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__UsersClient<runtime.Types.Result.GetResult<Prisma.$UsersPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Users that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UsersFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Users
   * const users = await prisma.users.findMany()
   * 
   * // Get first 10 Users
   * const users = await prisma.users.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const usersWithIdOnly = await prisma.users.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends UsersFindManyArgs>(args?: Prisma.SelectSubset<T, UsersFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$UsersPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Users.
   * @param {UsersCreateArgs} args - Arguments to create a Users.
   * @example
   * // Create one Users
   * const Users = await prisma.users.create({
   *   data: {
   *     // ... data to create a Users
   *   }
   * })
   * 
   */
  create<T extends UsersCreateArgs>(args: Prisma.SelectSubset<T, UsersCreateArgs<ExtArgs>>): Prisma.Prisma__UsersClient<runtime.Types.Result.GetResult<Prisma.$UsersPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Users.
   * @param {UsersCreateManyArgs} args - Arguments to create many Users.
   * @example
   * // Create many Users
   * const users = await prisma.users.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends UsersCreateManyArgs>(args?: Prisma.SelectSubset<T, UsersCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Users and returns the data saved in the database.
   * @param {UsersCreateManyAndReturnArgs} args - Arguments to create many Users.
   * @example
   * // Create many Users
   * const users = await prisma.users.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Users and only return the `id`
   * const usersWithIdOnly = await prisma.users.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends UsersCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, UsersCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$UsersPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Users.
   * @param {UsersDeleteArgs} args - Arguments to delete one Users.
   * @example
   * // Delete one Users
   * const Users = await prisma.users.delete({
   *   where: {
   *     // ... filter to delete one Users
   *   }
   * })
   * 
   */
  delete<T extends UsersDeleteArgs>(args: Prisma.SelectSubset<T, UsersDeleteArgs<ExtArgs>>): Prisma.Prisma__UsersClient<runtime.Types.Result.GetResult<Prisma.$UsersPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Users.
   * @param {UsersUpdateArgs} args - Arguments to update one Users.
   * @example
   * // Update one Users
   * const users = await prisma.users.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends UsersUpdateArgs>(args: Prisma.SelectSubset<T, UsersUpdateArgs<ExtArgs>>): Prisma.Prisma__UsersClient<runtime.Types.Result.GetResult<Prisma.$UsersPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Users.
   * @param {UsersDeleteManyArgs} args - Arguments to filter Users to delete.
   * @example
   * // Delete a few Users
   * const { count } = await prisma.users.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends UsersDeleteManyArgs>(args?: Prisma.SelectSubset<T, UsersDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Users.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UsersUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Users
   * const users = await prisma.users.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends UsersUpdateManyArgs>(args: Prisma.SelectSubset<T, UsersUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Users and returns the data updated in the database.
   * @param {UsersUpdateManyAndReturnArgs} args - Arguments to update many Users.
   * @example
   * // Update many Users
   * const users = await prisma.users.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Users and only return the `id`
   * const usersWithIdOnly = await prisma.users.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends UsersUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, UsersUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$UsersPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Users.
   * @param {UsersUpsertArgs} args - Arguments to update or create a Users.
   * @example
   * // Update or create a Users
   * const users = await prisma.users.upsert({
   *   create: {
   *     // ... data to create a Users
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Users we want to update
   *   }
   * })
   */
  upsert<T extends UsersUpsertArgs>(args: Prisma.SelectSubset<T, UsersUpsertArgs<ExtArgs>>): Prisma.Prisma__UsersClient<runtime.Types.Result.GetResult<Prisma.$UsersPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Users.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UsersCountArgs} args - Arguments to filter Users to count.
   * @example
   * // Count the number of Users
   * const count = await prisma.users.count({
   *   where: {
   *     // ... the filter for the Users we want to count
   *   }
   * })
  **/
  count<T extends UsersCountArgs>(
    args?: Prisma.Subset<T, UsersCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], UsersCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Users.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UsersAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends UsersAggregateArgs>(args: Prisma.Subset<T, UsersAggregateArgs>): Prisma.PrismaPromise<GetUsersAggregateType<T>>

  /**
   * Group by Users.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UsersGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends UsersGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: UsersGroupByArgs['orderBy'] }
      : { orderBy?: UsersGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, UsersGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetUsersGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Users model
 */
readonly fields: UsersFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Users.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__UsersClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  sessionss<T extends Prisma.Users$sessionssArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Users$sessionssArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SessionsPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  accountss<T extends Prisma.Users$accountssArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Users$accountssArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AccountsPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Users model
 */
export interface UsersFieldRefs {
  readonly id: Prisma.FieldRef<"Users", 'String'>
  readonly name: Prisma.FieldRef<"Users", 'String'>
  readonly email: Prisma.FieldRef<"Users", 'String'>
  readonly email_verified: Prisma.FieldRef<"Users", 'Boolean'>
  readonly image: Prisma.FieldRef<"Users", 'String'>
  readonly created_at: Prisma.FieldRef<"Users", 'DateTime'>
  readonly updated_at: Prisma.FieldRef<"Users", 'DateTime'>
  readonly username: Prisma.FieldRef<"Users", 'String'>
  readonly display_username: Prisma.FieldRef<"Users", 'String'>
}
    

// Custom InputTypes
/**
 * Users findUnique
 */
export type UsersFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Users
   */
  select?: Prisma.UsersSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Users
   */
  omit?: Prisma.UsersOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UsersInclude<ExtArgs> | null
  /**
   * Filter, which Users to fetch.
   */
  where: Prisma.UsersWhereUniqueInput
}

/**
 * Users findUniqueOrThrow
 */
export type UsersFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Users
   */
  select?: Prisma.UsersSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Users
   */
  omit?: Prisma.UsersOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UsersInclude<ExtArgs> | null
  /**
   * Filter, which Users to fetch.
   */
  where: Prisma.UsersWhereUniqueInput
}

/**
 * Users findFirst
 */
export type UsersFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Users
   */
  select?: Prisma.UsersSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Users
   */
  omit?: Prisma.UsersOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UsersInclude<ExtArgs> | null
  /**
   * Filter, which Users to fetch.
   */
  where?: Prisma.UsersWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Users to fetch.
   */
  orderBy?: Prisma.UsersOrderByWithRelationInput | Prisma.UsersOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Users.
   */
  cursor?: Prisma.UsersWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Users from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Users.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Users.
   */
  distinct?: Prisma.UsersScalarFieldEnum | Prisma.UsersScalarFieldEnum[]
}

/**
 * Users findFirstOrThrow
 */
export type UsersFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Users
   */
  select?: Prisma.UsersSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Users
   */
  omit?: Prisma.UsersOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UsersInclude<ExtArgs> | null
  /**
   * Filter, which Users to fetch.
   */
  where?: Prisma.UsersWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Users to fetch.
   */
  orderBy?: Prisma.UsersOrderByWithRelationInput | Prisma.UsersOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Users.
   */
  cursor?: Prisma.UsersWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Users from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Users.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Users.
   */
  distinct?: Prisma.UsersScalarFieldEnum | Prisma.UsersScalarFieldEnum[]
}

/**
 * Users findMany
 */
export type UsersFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Users
   */
  select?: Prisma.UsersSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Users
   */
  omit?: Prisma.UsersOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UsersInclude<ExtArgs> | null
  /**
   * Filter, which Users to fetch.
   */
  where?: Prisma.UsersWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Users to fetch.
   */
  orderBy?: Prisma.UsersOrderByWithRelationInput | Prisma.UsersOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Users.
   */
  cursor?: Prisma.UsersWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Users from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Users.
   */
  skip?: number
  distinct?: Prisma.UsersScalarFieldEnum | Prisma.UsersScalarFieldEnum[]
}

/**
 * Users create
 */
export type UsersCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Users
   */
  select?: Prisma.UsersSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Users
   */
  omit?: Prisma.UsersOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UsersInclude<ExtArgs> | null
  /**
   * The data needed to create a Users.
   */
  data: Prisma.XOR<Prisma.UsersCreateInput, Prisma.UsersUncheckedCreateInput>
}

/**
 * Users createMany
 */
export type UsersCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Users.
   */
  data: Prisma.UsersCreateManyInput | Prisma.UsersCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Users createManyAndReturn
 */
export type UsersCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Users
   */
  select?: Prisma.UsersSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Users
   */
  omit?: Prisma.UsersOmit<ExtArgs> | null
  /**
   * The data used to create many Users.
   */
  data: Prisma.UsersCreateManyInput | Prisma.UsersCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Users update
 */
export type UsersUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Users
   */
  select?: Prisma.UsersSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Users
   */
  omit?: Prisma.UsersOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UsersInclude<ExtArgs> | null
  /**
   * The data needed to update a Users.
   */
  data: Prisma.XOR<Prisma.UsersUpdateInput, Prisma.UsersUncheckedUpdateInput>
  /**
   * Choose, which Users to update.
   */
  where: Prisma.UsersWhereUniqueInput
}

/**
 * Users updateMany
 */
export type UsersUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Users.
   */
  data: Prisma.XOR<Prisma.UsersUpdateManyMutationInput, Prisma.UsersUncheckedUpdateManyInput>
  /**
   * Filter which Users to update
   */
  where?: Prisma.UsersWhereInput
  /**
   * Limit how many Users to update.
   */
  limit?: number
}

/**
 * Users updateManyAndReturn
 */
export type UsersUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Users
   */
  select?: Prisma.UsersSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Users
   */
  omit?: Prisma.UsersOmit<ExtArgs> | null
  /**
   * The data used to update Users.
   */
  data: Prisma.XOR<Prisma.UsersUpdateManyMutationInput, Prisma.UsersUncheckedUpdateManyInput>
  /**
   * Filter which Users to update
   */
  where?: Prisma.UsersWhereInput
  /**
   * Limit how many Users to update.
   */
  limit?: number
}

/**
 * Users upsert
 */
export type UsersUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Users
   */
  select?: Prisma.UsersSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Users
   */
  omit?: Prisma.UsersOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UsersInclude<ExtArgs> | null
  /**
   * The filter to search for the Users to update in case it exists.
   */
  where: Prisma.UsersWhereUniqueInput
  /**
   * In case the Users found by the `where` argument doesn't exist, create a new Users with this data.
   */
  create: Prisma.XOR<Prisma.UsersCreateInput, Prisma.UsersUncheckedCreateInput>
  /**
   * In case the Users was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.UsersUpdateInput, Prisma.UsersUncheckedUpdateInput>
}

/**
 * Users delete
 */
export type UsersDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Users
   */
  select?: Prisma.UsersSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Users
   */
  omit?: Prisma.UsersOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UsersInclude<ExtArgs> | null
  /**
   * Filter which Users to delete.
   */
  where: Prisma.UsersWhereUniqueInput
}

/**
 * Users deleteMany
 */
export type UsersDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Users to delete
   */
  where?: Prisma.UsersWhereInput
  /**
   * Limit how many Users to delete.
   */
  limit?: number
}

/**
 * Users.sessionss
 */
export type Users$sessionssArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Sessions
   */
  select?: Prisma.SessionsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Sessions
   */
  omit?: Prisma.SessionsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SessionsInclude<ExtArgs> | null
  where?: Prisma.SessionsWhereInput
  orderBy?: Prisma.SessionsOrderByWithRelationInput | Prisma.SessionsOrderByWithRelationInput[]
  cursor?: Prisma.SessionsWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.SessionsScalarFieldEnum | Prisma.SessionsScalarFieldEnum[]
}

/**
 * Users.accountss
 */
export type Users$accountssArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Accounts
   */
  select?: Prisma.AccountsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Accounts
   */
  omit?: Prisma.AccountsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AccountsInclude<ExtArgs> | null
  where?: Prisma.AccountsWhereInput
  orderBy?: Prisma.AccountsOrderByWithRelationInput | Prisma.AccountsOrderByWithRelationInput[]
  cursor?: Prisma.AccountsWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.AccountsScalarFieldEnum | Prisma.AccountsScalarFieldEnum[]
}

/**
 * Users without action
 */
export type UsersDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Users
   */
  select?: Prisma.UsersSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Users
   */
  omit?: Prisma.UsersOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UsersInclude<ExtArgs> | null
}
