
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Verifications` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model Verifications
 * 
 */
export type VerificationsModel = runtime.Types.Result.DefaultSelection<Prisma.$VerificationsPayload>

export type AggregateVerifications = {
  _count: VerificationsCountAggregateOutputType | null
  _min: VerificationsMinAggregateOutputType | null
  _max: VerificationsMaxAggregateOutputType | null
}

export type VerificationsMinAggregateOutputType = {
  id: string | null
  identifier: string | null
  value: string | null
  expires_at: Date | null
  created_at: Date | null
  updated_at: Date | null
}

export type VerificationsMaxAggregateOutputType = {
  id: string | null
  identifier: string | null
  value: string | null
  expires_at: Date | null
  created_at: Date | null
  updated_at: Date | null
}

export type VerificationsCountAggregateOutputType = {
  id: number
  identifier: number
  value: number
  expires_at: number
  created_at: number
  updated_at: number
  _all: number
}


export type VerificationsMinAggregateInputType = {
  id?: true
  identifier?: true
  value?: true
  expires_at?: true
  created_at?: true
  updated_at?: true
}

export type VerificationsMaxAggregateInputType = {
  id?: true
  identifier?: true
  value?: true
  expires_at?: true
  created_at?: true
  updated_at?: true
}

export type VerificationsCountAggregateInputType = {
  id?: true
  identifier?: true
  value?: true
  expires_at?: true
  created_at?: true
  updated_at?: true
  _all?: true
}

export type VerificationsAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Verifications to aggregate.
   */
  where?: Prisma.VerificationsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Verifications to fetch.
   */
  orderBy?: Prisma.VerificationsOrderByWithRelationInput | Prisma.VerificationsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.VerificationsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Verifications from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Verifications.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Verifications
  **/
  _count?: true | VerificationsCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: VerificationsMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: VerificationsMaxAggregateInputType
}

export type GetVerificationsAggregateType<T extends VerificationsAggregateArgs> = {
      [P in keyof T & keyof AggregateVerifications]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateVerifications[P]>
    : Prisma.GetScalarType<T[P], AggregateVerifications[P]>
}




export type VerificationsGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.VerificationsWhereInput
  orderBy?: Prisma.VerificationsOrderByWithAggregationInput | Prisma.VerificationsOrderByWithAggregationInput[]
  by: Prisma.VerificationsScalarFieldEnum[] | Prisma.VerificationsScalarFieldEnum
  having?: Prisma.VerificationsScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: VerificationsCountAggregateInputType | true
  _min?: VerificationsMinAggregateInputType
  _max?: VerificationsMaxAggregateInputType
}

export type VerificationsGroupByOutputType = {
  id: string
  identifier: string
  value: string
  expires_at: Date
  created_at: Date
  updated_at: Date
  _count: VerificationsCountAggregateOutputType | null
  _min: VerificationsMinAggregateOutputType | null
  _max: VerificationsMaxAggregateOutputType | null
}

type GetVerificationsGroupByPayload<T extends VerificationsGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<VerificationsGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof VerificationsGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], VerificationsGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], VerificationsGroupByOutputType[P]>
      }
    >
  >



export type VerificationsWhereInput = {
  AND?: Prisma.VerificationsWhereInput | Prisma.VerificationsWhereInput[]
  OR?: Prisma.VerificationsWhereInput[]
  NOT?: Prisma.VerificationsWhereInput | Prisma.VerificationsWhereInput[]
  id?: Prisma.UuidFilter<"Verifications"> | string
  identifier?: Prisma.StringFilter<"Verifications"> | string
  value?: Prisma.StringFilter<"Verifications"> | string
  expires_at?: Prisma.DateTimeFilter<"Verifications"> | Date | string
  created_at?: Prisma.DateTimeFilter<"Verifications"> | Date | string
  updated_at?: Prisma.DateTimeFilter<"Verifications"> | Date | string
}

export type VerificationsOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  identifier?: Prisma.SortOrder
  value?: Prisma.SortOrder
  expires_at?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
}

export type VerificationsWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.VerificationsWhereInput | Prisma.VerificationsWhereInput[]
  OR?: Prisma.VerificationsWhereInput[]
  NOT?: Prisma.VerificationsWhereInput | Prisma.VerificationsWhereInput[]
  identifier?: Prisma.StringFilter<"Verifications"> | string
  value?: Prisma.StringFilter<"Verifications"> | string
  expires_at?: Prisma.DateTimeFilter<"Verifications"> | Date | string
  created_at?: Prisma.DateTimeFilter<"Verifications"> | Date | string
  updated_at?: Prisma.DateTimeFilter<"Verifications"> | Date | string
}, "id">

export type VerificationsOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  identifier?: Prisma.SortOrder
  value?: Prisma.SortOrder
  expires_at?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
  _count?: Prisma.VerificationsCountOrderByAggregateInput
  _max?: Prisma.VerificationsMaxOrderByAggregateInput
  _min?: Prisma.VerificationsMinOrderByAggregateInput
}

export type VerificationsScalarWhereWithAggregatesInput = {
  AND?: Prisma.VerificationsScalarWhereWithAggregatesInput | Prisma.VerificationsScalarWhereWithAggregatesInput[]
  OR?: Prisma.VerificationsScalarWhereWithAggregatesInput[]
  NOT?: Prisma.VerificationsScalarWhereWithAggregatesInput | Prisma.VerificationsScalarWhereWithAggregatesInput[]
  id?: Prisma.UuidWithAggregatesFilter<"Verifications"> | string
  identifier?: Prisma.StringWithAggregatesFilter<"Verifications"> | string
  value?: Prisma.StringWithAggregatesFilter<"Verifications"> | string
  expires_at?: Prisma.DateTimeWithAggregatesFilter<"Verifications"> | Date | string
  created_at?: Prisma.DateTimeWithAggregatesFilter<"Verifications"> | Date | string
  updated_at?: Prisma.DateTimeWithAggregatesFilter<"Verifications"> | Date | string
}

export type VerificationsCreateInput = {
  id?: string
  identifier: string
  value: string
  expires_at: Date | string
  created_at?: Date | string
  updated_at?: Date | string
}

export type VerificationsUncheckedCreateInput = {
  id?: string
  identifier: string
  value: string
  expires_at: Date | string
  created_at?: Date | string
  updated_at?: Date | string
}

export type VerificationsUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  identifier?: Prisma.StringFieldUpdateOperationsInput | string
  value?: Prisma.StringFieldUpdateOperationsInput | string
  expires_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type VerificationsUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  identifier?: Prisma.StringFieldUpdateOperationsInput | string
  value?: Prisma.StringFieldUpdateOperationsInput | string
  expires_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type VerificationsCreateManyInput = {
  id?: string
  identifier: string
  value: string
  expires_at: Date | string
  created_at?: Date | string
  updated_at?: Date | string
}

export type VerificationsUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  identifier?: Prisma.StringFieldUpdateOperationsInput | string
  value?: Prisma.StringFieldUpdateOperationsInput | string
  expires_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type VerificationsUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  identifier?: Prisma.StringFieldUpdateOperationsInput | string
  value?: Prisma.StringFieldUpdateOperationsInput | string
  expires_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type VerificationsCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  identifier?: Prisma.SortOrder
  value?: Prisma.SortOrder
  expires_at?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
}

export type VerificationsMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  identifier?: Prisma.SortOrder
  value?: Prisma.SortOrder
  expires_at?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
}

export type VerificationsMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  identifier?: Prisma.SortOrder
  value?: Prisma.SortOrder
  expires_at?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
}



export type VerificationsSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  identifier?: boolean
  value?: boolean
  expires_at?: boolean
  created_at?: boolean
  updated_at?: boolean
}, ExtArgs["result"]["verifications"]>

export type VerificationsSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  identifier?: boolean
  value?: boolean
  expires_at?: boolean
  created_at?: boolean
  updated_at?: boolean
}, ExtArgs["result"]["verifications"]>

export type VerificationsSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  identifier?: boolean
  value?: boolean
  expires_at?: boolean
  created_at?: boolean
  updated_at?: boolean
}, ExtArgs["result"]["verifications"]>

export type VerificationsSelectScalar = {
  id?: boolean
  identifier?: boolean
  value?: boolean
  expires_at?: boolean
  created_at?: boolean
  updated_at?: boolean
}

export type VerificationsOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "identifier" | "value" | "expires_at" | "created_at" | "updated_at", ExtArgs["result"]["verifications"]>

export type $VerificationsPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Verifications"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    identifier: string
    value: string
    expires_at: Date
    created_at: Date
    updated_at: Date
  }, ExtArgs["result"]["verifications"]>
  composites: {}
}

export type VerificationsGetPayload<S extends boolean | null | undefined | VerificationsDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$VerificationsPayload, S>

export type VerificationsCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<VerificationsFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: VerificationsCountAggregateInputType | true
  }

export interface VerificationsDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Verifications'], meta: { name: 'Verifications' } }
  /**
   * Find zero or one Verifications that matches the filter.
   * @param {VerificationsFindUniqueArgs} args - Arguments to find a Verifications
   * @example
   * // Get one Verifications
   * const verifications = await prisma.verifications.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends VerificationsFindUniqueArgs>(args: Prisma.SelectSubset<T, VerificationsFindUniqueArgs<ExtArgs>>): Prisma.Prisma__VerificationsClient<runtime.Types.Result.GetResult<Prisma.$VerificationsPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Verifications that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {VerificationsFindUniqueOrThrowArgs} args - Arguments to find a Verifications
   * @example
   * // Get one Verifications
   * const verifications = await prisma.verifications.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends VerificationsFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, VerificationsFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__VerificationsClient<runtime.Types.Result.GetResult<Prisma.$VerificationsPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Verifications that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {VerificationsFindFirstArgs} args - Arguments to find a Verifications
   * @example
   * // Get one Verifications
   * const verifications = await prisma.verifications.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends VerificationsFindFirstArgs>(args?: Prisma.SelectSubset<T, VerificationsFindFirstArgs<ExtArgs>>): Prisma.Prisma__VerificationsClient<runtime.Types.Result.GetResult<Prisma.$VerificationsPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Verifications that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {VerificationsFindFirstOrThrowArgs} args - Arguments to find a Verifications
   * @example
   * // Get one Verifications
   * const verifications = await prisma.verifications.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends VerificationsFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, VerificationsFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__VerificationsClient<runtime.Types.Result.GetResult<Prisma.$VerificationsPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Verifications that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {VerificationsFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Verifications
   * const verifications = await prisma.verifications.findMany()
   * 
   * // Get first 10 Verifications
   * const verifications = await prisma.verifications.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const verificationsWithIdOnly = await prisma.verifications.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends VerificationsFindManyArgs>(args?: Prisma.SelectSubset<T, VerificationsFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$VerificationsPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Verifications.
   * @param {VerificationsCreateArgs} args - Arguments to create a Verifications.
   * @example
   * // Create one Verifications
   * const Verifications = await prisma.verifications.create({
   *   data: {
   *     // ... data to create a Verifications
   *   }
   * })
   * 
   */
  create<T extends VerificationsCreateArgs>(args: Prisma.SelectSubset<T, VerificationsCreateArgs<ExtArgs>>): Prisma.Prisma__VerificationsClient<runtime.Types.Result.GetResult<Prisma.$VerificationsPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Verifications.
   * @param {VerificationsCreateManyArgs} args - Arguments to create many Verifications.
   * @example
   * // Create many Verifications
   * const verifications = await prisma.verifications.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends VerificationsCreateManyArgs>(args?: Prisma.SelectSubset<T, VerificationsCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Verifications and returns the data saved in the database.
   * @param {VerificationsCreateManyAndReturnArgs} args - Arguments to create many Verifications.
   * @example
   * // Create many Verifications
   * const verifications = await prisma.verifications.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Verifications and only return the `id`
   * const verificationsWithIdOnly = await prisma.verifications.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends VerificationsCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, VerificationsCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$VerificationsPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Verifications.
   * @param {VerificationsDeleteArgs} args - Arguments to delete one Verifications.
   * @example
   * // Delete one Verifications
   * const Verifications = await prisma.verifications.delete({
   *   where: {
   *     // ... filter to delete one Verifications
   *   }
   * })
   * 
   */
  delete<T extends VerificationsDeleteArgs>(args: Prisma.SelectSubset<T, VerificationsDeleteArgs<ExtArgs>>): Prisma.Prisma__VerificationsClient<runtime.Types.Result.GetResult<Prisma.$VerificationsPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Verifications.
   * @param {VerificationsUpdateArgs} args - Arguments to update one Verifications.
   * @example
   * // Update one Verifications
   * const verifications = await prisma.verifications.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends VerificationsUpdateArgs>(args: Prisma.SelectSubset<T, VerificationsUpdateArgs<ExtArgs>>): Prisma.Prisma__VerificationsClient<runtime.Types.Result.GetResult<Prisma.$VerificationsPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Verifications.
   * @param {VerificationsDeleteManyArgs} args - Arguments to filter Verifications to delete.
   * @example
   * // Delete a few Verifications
   * const { count } = await prisma.verifications.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends VerificationsDeleteManyArgs>(args?: Prisma.SelectSubset<T, VerificationsDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Verifications.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {VerificationsUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Verifications
   * const verifications = await prisma.verifications.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends VerificationsUpdateManyArgs>(args: Prisma.SelectSubset<T, VerificationsUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Verifications and returns the data updated in the database.
   * @param {VerificationsUpdateManyAndReturnArgs} args - Arguments to update many Verifications.
   * @example
   * // Update many Verifications
   * const verifications = await prisma.verifications.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Verifications and only return the `id`
   * const verificationsWithIdOnly = await prisma.verifications.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends VerificationsUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, VerificationsUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$VerificationsPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Verifications.
   * @param {VerificationsUpsertArgs} args - Arguments to update or create a Verifications.
   * @example
   * // Update or create a Verifications
   * const verifications = await prisma.verifications.upsert({
   *   create: {
   *     // ... data to create a Verifications
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Verifications we want to update
   *   }
   * })
   */
  upsert<T extends VerificationsUpsertArgs>(args: Prisma.SelectSubset<T, VerificationsUpsertArgs<ExtArgs>>): Prisma.Prisma__VerificationsClient<runtime.Types.Result.GetResult<Prisma.$VerificationsPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Verifications.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {VerificationsCountArgs} args - Arguments to filter Verifications to count.
   * @example
   * // Count the number of Verifications
   * const count = await prisma.verifications.count({
   *   where: {
   *     // ... the filter for the Verifications we want to count
   *   }
   * })
  **/
  count<T extends VerificationsCountArgs>(
    args?: Prisma.Subset<T, VerificationsCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], VerificationsCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Verifications.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {VerificationsAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends VerificationsAggregateArgs>(args: Prisma.Subset<T, VerificationsAggregateArgs>): Prisma.PrismaPromise<GetVerificationsAggregateType<T>>

  /**
   * Group by Verifications.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {VerificationsGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends VerificationsGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: VerificationsGroupByArgs['orderBy'] }
      : { orderBy?: VerificationsGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, VerificationsGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetVerificationsGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Verifications model
 */
readonly fields: VerificationsFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Verifications.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__VerificationsClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Verifications model
 */
export interface VerificationsFieldRefs {
  readonly id: Prisma.FieldRef<"Verifications", 'String'>
  readonly identifier: Prisma.FieldRef<"Verifications", 'String'>
  readonly value: Prisma.FieldRef<"Verifications", 'String'>
  readonly expires_at: Prisma.FieldRef<"Verifications", 'DateTime'>
  readonly created_at: Prisma.FieldRef<"Verifications", 'DateTime'>
  readonly updated_at: Prisma.FieldRef<"Verifications", 'DateTime'>
}
    

// Custom InputTypes
/**
 * Verifications findUnique
 */
export type VerificationsFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Verifications
   */
  select?: Prisma.VerificationsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Verifications
   */
  omit?: Prisma.VerificationsOmit<ExtArgs> | null
  /**
   * Filter, which Verifications to fetch.
   */
  where: Prisma.VerificationsWhereUniqueInput
}

/**
 * Verifications findUniqueOrThrow
 */
export type VerificationsFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Verifications
   */
  select?: Prisma.VerificationsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Verifications
   */
  omit?: Prisma.VerificationsOmit<ExtArgs> | null
  /**
   * Filter, which Verifications to fetch.
   */
  where: Prisma.VerificationsWhereUniqueInput
}

/**
 * Verifications findFirst
 */
export type VerificationsFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Verifications
   */
  select?: Prisma.VerificationsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Verifications
   */
  omit?: Prisma.VerificationsOmit<ExtArgs> | null
  /**
   * Filter, which Verifications to fetch.
   */
  where?: Prisma.VerificationsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Verifications to fetch.
   */
  orderBy?: Prisma.VerificationsOrderByWithRelationInput | Prisma.VerificationsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Verifications.
   */
  cursor?: Prisma.VerificationsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Verifications from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Verifications.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Verifications.
   */
  distinct?: Prisma.VerificationsScalarFieldEnum | Prisma.VerificationsScalarFieldEnum[]
}

/**
 * Verifications findFirstOrThrow
 */
export type VerificationsFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Verifications
   */
  select?: Prisma.VerificationsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Verifications
   */
  omit?: Prisma.VerificationsOmit<ExtArgs> | null
  /**
   * Filter, which Verifications to fetch.
   */
  where?: Prisma.VerificationsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Verifications to fetch.
   */
  orderBy?: Prisma.VerificationsOrderByWithRelationInput | Prisma.VerificationsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Verifications.
   */
  cursor?: Prisma.VerificationsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Verifications from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Verifications.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Verifications.
   */
  distinct?: Prisma.VerificationsScalarFieldEnum | Prisma.VerificationsScalarFieldEnum[]
}

/**
 * Verifications findMany
 */
export type VerificationsFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Verifications
   */
  select?: Prisma.VerificationsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Verifications
   */
  omit?: Prisma.VerificationsOmit<ExtArgs> | null
  /**
   * Filter, which Verifications to fetch.
   */
  where?: Prisma.VerificationsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Verifications to fetch.
   */
  orderBy?: Prisma.VerificationsOrderByWithRelationInput | Prisma.VerificationsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Verifications.
   */
  cursor?: Prisma.VerificationsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Verifications from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Verifications.
   */
  skip?: number
  distinct?: Prisma.VerificationsScalarFieldEnum | Prisma.VerificationsScalarFieldEnum[]
}

/**
 * Verifications create
 */
export type VerificationsCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Verifications
   */
  select?: Prisma.VerificationsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Verifications
   */
  omit?: Prisma.VerificationsOmit<ExtArgs> | null
  /**
   * The data needed to create a Verifications.
   */
  data: Prisma.XOR<Prisma.VerificationsCreateInput, Prisma.VerificationsUncheckedCreateInput>
}

/**
 * Verifications createMany
 */
export type VerificationsCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Verifications.
   */
  data: Prisma.VerificationsCreateManyInput | Prisma.VerificationsCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Verifications createManyAndReturn
 */
export type VerificationsCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Verifications
   */
  select?: Prisma.VerificationsSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Verifications
   */
  omit?: Prisma.VerificationsOmit<ExtArgs> | null
  /**
   * The data used to create many Verifications.
   */
  data: Prisma.VerificationsCreateManyInput | Prisma.VerificationsCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Verifications update
 */
export type VerificationsUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Verifications
   */
  select?: Prisma.VerificationsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Verifications
   */
  omit?: Prisma.VerificationsOmit<ExtArgs> | null
  /**
   * The data needed to update a Verifications.
   */
  data: Prisma.XOR<Prisma.VerificationsUpdateInput, Prisma.VerificationsUncheckedUpdateInput>
  /**
   * Choose, which Verifications to update.
   */
  where: Prisma.VerificationsWhereUniqueInput
}

/**
 * Verifications updateMany
 */
export type VerificationsUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Verifications.
   */
  data: Prisma.XOR<Prisma.VerificationsUpdateManyMutationInput, Prisma.VerificationsUncheckedUpdateManyInput>
  /**
   * Filter which Verifications to update
   */
  where?: Prisma.VerificationsWhereInput
  /**
   * Limit how many Verifications to update.
   */
  limit?: number
}

/**
 * Verifications updateManyAndReturn
 */
export type VerificationsUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Verifications
   */
  select?: Prisma.VerificationsSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Verifications
   */
  omit?: Prisma.VerificationsOmit<ExtArgs> | null
  /**
   * The data used to update Verifications.
   */
  data: Prisma.XOR<Prisma.VerificationsUpdateManyMutationInput, Prisma.VerificationsUncheckedUpdateManyInput>
  /**
   * Filter which Verifications to update
   */
  where?: Prisma.VerificationsWhereInput
  /**
   * Limit how many Verifications to update.
   */
  limit?: number
}

/**
 * Verifications upsert
 */
export type VerificationsUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Verifications
   */
  select?: Prisma.VerificationsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Verifications
   */
  omit?: Prisma.VerificationsOmit<ExtArgs> | null
  /**
   * The filter to search for the Verifications to update in case it exists.
   */
  where: Prisma.VerificationsWhereUniqueInput
  /**
   * In case the Verifications found by the `where` argument doesn't exist, create a new Verifications with this data.
   */
  create: Prisma.XOR<Prisma.VerificationsCreateInput, Prisma.VerificationsUncheckedCreateInput>
  /**
   * In case the Verifications was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.VerificationsUpdateInput, Prisma.VerificationsUncheckedUpdateInput>
}

/**
 * Verifications delete
 */
export type VerificationsDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Verifications
   */
  select?: Prisma.VerificationsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Verifications
   */
  omit?: Prisma.VerificationsOmit<ExtArgs> | null
  /**
   * Filter which Verifications to delete.
   */
  where: Prisma.VerificationsWhereUniqueInput
}

/**
 * Verifications deleteMany
 */
export type VerificationsDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Verifications to delete
   */
  where?: Prisma.VerificationsWhereInput
  /**
   * Limit how many Verifications to delete.
   */
  limit?: number
}

/**
 * Verifications without action
 */
export type VerificationsDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Verifications
   */
  select?: Prisma.VerificationsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Verifications
   */
  omit?: Prisma.VerificationsOmit<ExtArgs> | null
}
